apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dvanhu/gitops-nginx:cfb8876074be51ce3ffc4a4032cf31db4979ae79
        ports:
        - containerPort: 80
