apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dvanhu/gitops-nginx:48efb5f4f879ef27901c27401af98a63ca778007
        ports:
        - containerPort: 80
