apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dvanhu/gitops-nginx:82e14f448f4851d1a1607b4ec641477d8db5d09f
        ports:
        - containerPort: 80
