apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: dvanhu/gitops-nginx:ed33303fa9ad888d2fe24f5258ed5c5d7831fc24 
